stages:
  data_ingestion:
    cmd: python src/dataload.py
    deps:
    - src/dataload.py
    params:
    - data load.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  model_building:
    cmd: python src/model.py
    deps:
    - data/interim
    - src/model.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - model/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
# params:
# - dvclive/params.yaml
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
